spring:
  profiles:
    active: prod
  cache:
    type: redis
  application:
    name: qywx-example
  jackson:
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://81.70.26.22:3306/neusoft
    username: neusoft
    password: 4zp6f2HZjZXaAaf2
    driverClassName: com.mysql.cj.jdbc.Driver
  redis: # 更正后的 Redis 配置
    database: 0
    host: 127.0.0.1
    password: 12345678
    port: 6379

server:
  port: 8088

# 启用调试模式
debug: true
